spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: false
    template:
      reply-timeout: 15000
      retry:
        enabled: false
  data:
    neo4j:
      uri: bolt://groupdb:7687
      username: neo4j
      password: neo4j
  application:
    name: group-service

server:
  port: 9102

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: group-service

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO